'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Donar

    '''<summary>
    '''dfname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dfname As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''dlname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dlname As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''daddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents daddress As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''dpin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dpin As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlst As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlds control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlds As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlci control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlci As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''dphone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dphone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''dpan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dpan As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''demail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents demail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''dpass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dpass As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BtndRegister control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtndRegister As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''gvd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvd As Global.System.Web.UI.WebControls.GridView
End Class
