'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class individuals

    '''<summary>
    '''ilname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ilname As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''iaddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents iaddress As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ipin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ipin As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddst As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddds control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddds As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddci control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddci As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''iphone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents iphone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ipan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ipan As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''iacc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents iacc As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''iemail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents iemail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ipass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ipass As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''icond control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents icond As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''isup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents isup As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BtnIRegister control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnIRegister As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''gvind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvind As Global.System.Web.UI.WebControls.GridView
End Class
